---
title: "Web_Scraping"
author: "David Barnes"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(rvest)
library(doParallel)
library(foreach)
library(textstem)
library(tm)
library(readr)
library(httr)
library(tidytext)
```

```{r eval = FALSE}
getStockData <- function(stockTicker) {
  # API KEY
  avKey <- "REDACTED"
  baseLink <- "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&outputsize=full&symbol="

    avLinkGenerator <- paste(baseLink, 
                              stockTicker, "&interval=60min", "&datatype=csv",
                              "&apikey=", avKey, sep = "")
    
  avRequest <- GET(avLinkGenerator)
  avParsed <- read.delim(text = httr::content(avRequest, as = "text"), sep = ",")
  avParsed$timestamp <- as.Date(avParsed$timestamp)
  return(avParsed)
}

SPY_data <- getStockData("SPY")
save(SPY_data, file = "./data/SPY_Data.Rdata")
```


```{r eval = FALSE}
speeches_get <- GET("https://www.federalreserve.gov/json/ne-speeches.json")
```

```{r eval = FALSE}
cl <- makeCluster(detectCores() - 1) 

registerDoParallel(cl)

t1 <- proc.time()

speeches <- content(speeches_get) %>%
  bind_rows() %>%
  transmute(Name = t,
            url = str_replace(l, "//", "/"), #rid of the "//" at the beginning of the url
            url = paste0("https://www.federalreserve.gov/", url)) %>%
  filter(!is.na(Name)) # filtering NA as the last row of the json is not a speech
speeches$speech_transcript <- "" # making sure the column speech_transcript works before I try to assign its values in the loop


for (i in 1:nrow(speeches)) { # going through urls and getting the text of the speeches
  speeches[i,]$speech_transcript <- read_html(speeches[i,]$url) %>%
    html_node("#content") %>%
    html_node("#article") %>%
    html_node("div:nth-child(3)") %>%
    html_text() %>%
    str_squish() # getting rid of multiple spaces and stuff
print(i)
}
# get the date from the speeches

speeches$date <- ""

for (i in 1:nrow(speeches)) {
  speeches[i,]$date <- read_html(speeches[i,]$url) %>% 
    html_node("#content") %>%
    html_node("p") %>%
    html_text()
  
  print(i)
}

test_names <- data.frame("testing")
test_names$X.testing. <- ""

read_html(speeches[1,]$url) %>%
  html_node("#content") %>%
  html_node("#article") %>%
  html_node("heading col-xs-12 col-sm-8 col-md-8") %>%
  html_text()
#  html_node("speaker") %>%
#  html_text()

for (i in 1:nrow(speeches)) {
  test_names[i,]$X.testing <- read_html(speeches[i,]$url) %>% 
    html_node("#content") %>%
    html_node("speaker") %>%
    html_text()
  
  print(i)
}

proc.time() - t1

stopCluster(cl)

save(speeches, file = "./data/Speeches_Data.Rdata")
```

```{r eval = FALSE}
# cl <- makeCluster(detectCores() - 1)
# 
# registerDoParallel(cl)
# 
# t1 <- proc.time()
# # grab speeches
# speeches <- content(speeches_get) %>%
#   bind_rows() %>%
#   transmute(Name = t,
#             url = str_replace(l, "//", "/"), #rid of the "//" at the beginning of the url
#             url = paste0("https://www.federalreserve.gov/", url)) %>%
#   filter(!is.na(Name)) # filtering NA as the last row of the json is not a speech
# speeches$speech_transcript <- "" # making sure the column speech_transcript works before I try to assign its values in the loop
# 
# speeches <- speeches[1:100,]
# 
# # loop through the speeches
# speech_parallel <- foreach(i = 1:nrow(speeches), .packages = c("tidyverse", "httr", "rvest")) %dopar% { # going through urls and getting the text of the speeches
#   speeches[i,]$speech_transcript <- read_html(speeches[i,]$url) %>%
#     html_node("#content") %>%
#     html_node("#article") %>%
#     html_node("div:nth-child(3)") %>%
#     html_text() %>%
#     str_squish() # getting rid of multiple spaces and stuff
# }
# 
# df <- data.frame(matrix(unlist(speech_parallel), nrow=length(speech_parallel), byrow=TRUE))
# 
# for(i in speech_parallel) {
#   speeches$speech_transcript[i,] <- data.frame(speech_parallel[[i]])
# }
# 
# 
# 
# proc.time() - t1  
# 
# stopCluster(cl)
```

```{r}
# load("./Speeches.RData")
load("./data/Speeches_Data.Rdata")
```


All 848 speeches from federal reserve. Probably shouldn't have done this much as it was really hard on my computer, but it was too tempting (sentiment analysis vs SP500 in future?).

```{r}
# example1 <-speeches$speech_transcript[1]
# example1 #full speech
speech_text <- speeches$speech_transcript
```

```{r Text Cleaning}
# remove doubleback slashes and single backslashes
speech_text <- gsub("\\\\", "", speech_text)
speech_text <- gsub("\"", "", speech_text)
# remove parenthesis and their contents
speech_text <- gsub("\\s*\\([^\\)]+\\)", "", speech_text)
# remove hyperlinks until a space is found
speech_text <- gsub(" ?(f|ht)(tp)s?(://)(\\S*)[./](\\S*)", "", speech_text)
# remove small strings/words that are in the text
speech_text <- gsub("pp.", "", speech_text)
speech_text <- gsub("vol.", "", speech_text)
# remove punctuation and various symbols
speech_text <- tm::removePunctuation(speech_text)
speech_text <- gsub("–", "", speech_text)
speech_text <- stripWhitespace(speech_text)
# remove stopwords
speech_text <- removeWords(speech_text, stopwords("en"))
speech_text <- tolower(speech_text)
# remove "return text" string which is prevalent in many speeches
speech_text <- gsub("return text", "", speech_text)
# remove this special dash from speeches
speech_text <- gsub(" — ", "", speech_text)
# remove numbers
speech_text <- removeNumbers(speech_text)


head(speech_text, n = 1)
# looks pretty good now, lets lemmatize
```

```{r}
speech_text <- lemmatize_strings(speech_text)
head(speech_text, n = 1)
```

```{r}
speeches$rowindex <- rownames(speeches)

speech_text <- data.frame(speech_text)
colnames(speech_text) <- "calltext"

tokens <- speech_text %>%
  group_by(rownames(speech_text)) %>%
  unnest_tokens(tbl = ., output = word, input = calltext)

sent_tokens <- tokens %>%
  inner_join(get_sentiments("loughran")) %>%
  count(sentiment) %>%
  tidyr::pivot_wider(values_from = n, names_from = sentiment, values_fill = 0) %>%
  mutate(sentiment = positive - negative)

names(sent_tokens)[names(sent_tokens) == 'rownames(speech_text)'] <- 'rowindex'

speeches_sent <- left_join(speeches, sent_tokens, by.x = 'rowindex', by.y = "rowindex") 

head(speeches_sent$date)

speeches_sent$date <- as.Date(speeches_sent$date, format = "%b %d, %y")

head(speeches_sent$date)

speeches_sent$sentiment <- as.numeric(speeches_sent$sentiment)

speeches_sent$speech_transcript <- ""

speeches_agg_sent <- speeches_sent %>%
  group_by(date) %>%
  select(date, sentiment) %>%
  mutate_each(funs(replace(sentiment, which(is.na(.)), 1))) %>% # NA values <- 0 in sentiment column
  summarise(sentiment = mean(sentiment))
```
```{r}
library(ggplot2)

#constraining
ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred") + 
  geom_line(aes(y = constraining), color = "steelblue")
```
```{r}
#litigious
ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred") + 
  geom_line(aes(y = litigious), color = "yellow")
```
```{r}
#negative
ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred") + 
  geom_line(aes(y = negative), color = "green")
```
```{r}
#positive
ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred", linetype = "twodash") + 
  geom_line(aes(y = positive), color = "purple", linetype = "twodash")
```
```{r}
#uncertainty
uncertainty <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred", linetype = "twodash") + 
  geom_line(aes(y = uncertainty), color = "steelblue", linetype = "twodash")
```
```{r}
#superfluous
superfluous <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred", linetype = "twodash") + 
  geom_line(aes(y = superfluous), color = "steelblue", linetype = "twodash")
```

```{r}
ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "darkred", linetype = "twodash") + 
  geom_line(aes(y = constraining), color = "steelblue", linetype = "twodash") +
  geom_line(aes(y = litigious), color = "yellow", linetype = "twodash") +
  geom_line(aes(y = uncertainty), color = "green", linetype = "twodash") +
  geom_line(aes(y = superfluous), color = "purple", linetype = "twodash") 


```
```{r}
library(ggplot2)
library(ggpubr)

sentiment <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = sentiment), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

constraining <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = constraining), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

litigious <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = litigious), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank()) 

negative <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = negative), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

positive <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = positive), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

uncertainty <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = uncertainty), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

superfluous <- ggplot(speeches_sent, aes(x=date)) + 
  geom_line(aes(y = superfluous), color = "steelblue") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

ggarrange(sentiment, constraining, litigious, negative, positive, uncertainty, superfluous)


```

```{r}
library(ggplot2)
library(ggpubr)

sentiment_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = sentiment), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

constraining_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = constraining), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

litigious_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = litigious), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

negative_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = negative), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

positive_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = positive), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

uncertainty_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = uncertainty), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

superfluous_smooth <- ggplot(speeches_sent, aes(x=date)) + 
  geom_smooth(aes(y = superfluous), color = "gold") +
  theme(axis.text.x =  element_blank(),
        axis.ticks.x = element_blank())

ggarrange(sentiment_smooth, constraining_smooth, litigious_smooth, negative_smooth, positive_smooth, uncertainty_smooth, superfluous_smooth)
```


